#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

function safe(cmd) {
  try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return ''; }
}

function canonicalJson(v) {
  if (v === null || typeof v !== 'object') return JSON.stringify(v);
  if (Array.isArray(v)) return '[' + v.map(canonicalJson).join(',') + ']';
  const keys = Object.keys(v).sort();
  return '{' + keys.map(k => JSON.stringify(k) + ':' + canonicalJson(v[k])).join(',') + '}';
}

const sha = safe('git rev-parse HEAD') || 'unknown';
const status = safe('git status --porcelain');
const dirty = status.length > 0;
const ts = new Date().toISOString();

const policyJson = JSON.parse(readFileSync('capabilities.json', 'utf8'));
const policyHash = createHash('sha256').update(canonicalJson(policyJson)).digest('hex');
const policyVersion = policyJson.version;

const body =
`// generated by scripts/embed-version.mjs — do not edit
export const VERSION_ID = Object.freeze({
  sha: ${JSON.stringify(sha)},
  ts: ${JSON.stringify(ts)},
  dirty: ${dirty},
});
export const POLICY_HASH = ${JSON.stringify(policyHash)};
export const POLICY_VERSION = ${JSON.stringify(policyVersion)};
export function versionString() {
  return VERSION_ID.sha.slice(0, 12) + '@' + VERSION_ID.ts + (VERSION_ID.dirty ? '-dirty' : '');
}
`;

writeFileSync('src/lib/version-id.ts', body);
console.error(`Embedded version ${sha.slice(0, 12)}${dirty ? ' (dirty)' : ''}, policy_hash=${policyHash.slice(0, 12)}`);

if (process.env.CI === 'true' && dirty && process.env.BHG_ALLOW_DIRTY_BUILD !== '1') {
  console.error('Refusing to build a dirty tree in CI. Commit changes or set BHG_ALLOW_DIRTY_BUILD=1.');
  process.exit(1);
}
