#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

function safe(cmd) {
  try { return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); }
  catch { return ''; }
}

const sha = safe('git rev-parse HEAD') || 'unknown';
const status = safe('git status --porcelain');
const dirty = status.length > 0;
const ts = new Date().toISOString();

const body =
`// generated by scripts/embed-version.mjs — do not edit
export const VERSION_ID = Object.freeze({
  sha: ${JSON.stringify(sha)},
  ts: ${JSON.stringify(ts)},
  dirty: ${dirty},
});
export function versionString() {
  return VERSION_ID.sha.slice(0, 12) + '@' + VERSION_ID.ts + (VERSION_ID.dirty ? '-dirty' : '');
}
`;

writeFileSync('src/lib/version-id.ts', body);
console.error(`Embedded version ${sha.slice(0, 12)}${dirty ? ' (dirty)' : ''}`);

if (process.env.CI === 'true' && dirty && process.env.BHG_ALLOW_DIRTY_BUILD !== '1') {
  console.error('Refusing to build a dirty tree in CI. Commit changes or set BHG_ALLOW_DIRTY_BUILD=1.');
  process.exit(1);
}
